library 'ModelonCommon@trunk'

node('92PR2T2'){
  pipeline {
      agent {
          docker {
              image 'node:12-alpine'
          }
      }
      environment { 
          CI = 'true'
      }
      stages {
          stage('Build') {
              steps {
                  sh 'npm install'
                  sh 'npm run build'
              }
          }
          stage('Test') {
              steps {
                  sh 'npm test'
              }
          }
      }
  }
}
